
name: Process Scheduling Submission

on:
  discussion:
    types: [created]
  issues:
    types: [opened]

jobs:
  process-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Process new submission
        run: node scripts/process-submission.js "${{ toJSON(github.event) }}"

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/submissions.json
          git diff --staged --quiet || git commit -m "添加新的排班提交"
          git push
